name: CI

on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - 8.2
          - 8.3
          - 8.4
    name: Tests on PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: "php${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php${{ matrix.php-versions }}-composer-"

      - name: Install dependencies
        run: composer update && composer install

      - name: Run tests
        run: composer test
